In [2]:
import pandas as pd

df = pd.read_csv("/content/ganga_water_quality_2011_2015.csv")

df.head()

,Sr. No.,LOCATION - Water Quality Criteria,DO (mg/l) - 2011 - >5 mg/l,DO (mg/l) - 2012 - >5 mg/l,DO (mg/l) - 2013 - >5 mg/l,DO (mg/l) - 2014 - >5 mg/l,DO (mg/l) - 2015 - >5 mg/l,B.O.D (mg/l) - 2011 - < 3 mg/l,B.O.D (mg/l) - 2012 - < 3 mg/l,B.O.D (mg/l) - 2013 - < 3 mg/l,B.O.D (mg/l) - 2014 - < 3 mg/l,B.O.D (mg/l) - 2015 - < 3 mg/l,FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml,FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml,FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml,FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml,FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml
0,1,GANGA AT HARIDWAR D/S,6.7,7.2,6.5,5.0,9.2,5.6,5.3,5.2,5.2,2.8,1150,NaN,NaN,NaN,580
1,2,GANGA AT GARHMUKTESHWAR,8.2,8.6,9.0,9.1,7.7,3.4,3.4,2.9,2.8,3.0,1162,920.0,767.0,725.0,733
2,3,GANGA AT KANNAUJ U/S (RAJGHAT),7.9,8.6,8.2,7.8,8.4,4.5,4.0,4.0,2.8,3.5,3042,4673.0,1210.0,3500.0,2270
3,4,"GANGA AT KANNAUJ D/S, U.P",7.8,8.3,7.9,5.8,7.9,5.5,4.8,4.3,3.0,3.7,3508,6045.0,1517.0,4000.0,2930
4,5,GANGA AT KANPUR U/S (RANIGHAT),8.6,8.7,8.3,7.8,8.2,4.3,4.3,3.4,3.5,2.9,6667,6245.0,1358.0,4200.0,3267

In [3]:
df.shape

(10, 17)

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Sr. No.                                               10 non-null     int64
 1   LOCATION - Water Quality Criteria                     10 non-null     object
 2   DO (mg/l) - 2011 - >5 mg/l                            10 non-null     float64
 3   DO (mg/l) - 2012 - >5 mg/l                            10 non-null     float64
 4   DO (mg/l) - 2013 - >5 mg/l                            10 non-null     float64
 5   DO (mg/l) - 2014 - >5 mg/l                            10 non-null     float64
 6   DO (mg/l) - 2015 - >5 mg/l                            10 non-null     float64
 7   B.O.D (mg/l) - 2011 - < 3 mg/l                        10 non-null     float64
 8   B.O.D (mg/l) - 2012 - < 3 mg/l                        10 non-null     float64
 9   B.O.D (mg/l) - 2013 - < 3 mg/l                        10 non-null     float64
 10  B.O.D (mg/l) - 2014 - < 3 mg/l                        10 non-null     float64
 11  B.O.D (mg/l) - 2015 - < 3 mg/l                        10 non-null     float64
 12  FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml  10 non-null     int64
 13  FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml  9 non-null      float64
 14  FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml  9 non-null      float64
 15  FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml  9 non-null      float64
 16  FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml  10 non-null     int64
dtypes: float64(13), int64(3), object(1)
memory usage: 1.5+ KB

Sr. No.                                                 0
LOCATION - Water Quality Criteria                       0
DO (mg/l) - 2011 - >5 mg/l                              0
DO (mg/l) - 2012 - >5 mg/l                              0
DO (mg/l) - 2013 - >5 mg/l                              0
DO (mg/l) - 2014 - >5 mg/l                              0
DO (mg/l) - 2015 - >5 mg/l                              0
B.O.D (mg/l) - 2011 - < 3 mg/l                          0
B.O.D (mg/l) - 2012 - < 3 mg/l                          0
B.O.D (mg/l) - 2013 - < 3 mg/l                          0
B.O.D (mg/l) - 2014 - < 3 mg/l                          0
B.O.D (mg/l) - 2015 - < 3 mg/l                          0
FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml    0
FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml    1
FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml    1
FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml    1
FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml    0
dtype: int64

In [5]:
df = df.dropna(axis=1, how="all")

In [6]:
df.shape

(10, 17)

In [7]:
print(df.columns.tolist())

['Sr. No.', 'LOCATION - Water Quality Criteria', 'DO (mg/l) - 2011 - >5 mg/l', 'DO (mg/l) - 2012 - >5 mg/l', 'DO (mg/l) - 2013 - >5 mg/l', 'DO (mg/l) - 2014 - >5 mg/l', 'DO (mg/l) - 2015 - >5 mg/l', 'B.O.D (mg/l) - 2011 - < 3 mg/l', 'B.O.D (mg/l) - 2012 - < 3 mg/l', 'B.O.D (mg/l) - 2013 - < 3 mg/l', 'B.O.D (mg/l) - 2014 - < 3 mg/l', 'B.O.D (mg/l) - 2015 - < 3 mg/l', 'FECAL COLIFORM (MPN/100ml) - 2011 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2012 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2013 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2014 - < 2500 MPN/100ml', 'FECAL COLIFORM (MPN/100ml) - 2015 - < 2500 MPN/100ml']

In [8]:
df.columns = [
    "sr_no",
    "location",
    "do_2011",
    "do_2012",
    "do_2013",
    "do_2014",
    "do_2015",
    "bod_2011",
    "bod_2012",
    "bod_2013",
    "bod_2014",
    "bod_2015",
    "fecal_coliform_2011",
    "fecal_coliform_2012",
    "fecal_coliform_2013",
    "fecal_coliform_2014",
    "fecal_coliform_2015"
]

In [9]:
df = df.replace("NA", pd.NA)

In [10]:
df.isnull().sum()

sr_no                  0
location               0
do_2011                0
do_2012                0
do_2013                0
do_2014                0
do_2015                0
bod_2011               0
bod_2012               0
bod_2013               0
bod_2014               0
bod_2015               0
fecal_coliform_2011    0
fecal_coliform_2012    1
fecal_coliform_2013    1
fecal_coliform_2014    1
fecal_coliform_2015    0
dtype: int64

In [11]:
numeric_columns = [
    "do_2011", "do_2012", "do_2013", "do_2014", "do_2015",
    "bod_2011", "bod_2012", "bod_2013", "bod_2014", "bod_2015",
    "fecal_coliform_2011", "fecal_coliform_2012",
    "fecal_coliform_2013", "fecal_coliform_2014",
    "fecal_coliform_2015"
]

df[numeric_columns] = df[numeric_columns].apply(
    pd.to_numeric, errors="coerce"
)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop_duplicates()

In [14]:
df["location"].unique()

array(['GANGA AT HARIDWAR D/S', 'GANGA AT GARHMUKTESHWAR',
       'GANGA AT KANNAUJ U/S (RAJGHAT)', 'GANGA AT KANNAUJ D/S, U.P',
       'GANGA AT KANPUR U/S (RANIGHAT)',
       'GANGA AT KANPUR D/S (JAJMAU PUMPING STATION)',
       'GANGA AT ALLAHABAD D/S (SANGAM), U.P.',
       'GANGA AT VARANASI D/S (MALVIYA BRIDGE), U.P',
       'GANGA AT TRIGHAT (GHAZIPUR)', 'GANGA AT DAKSHINESHWAR'],
      dtype=object)

In [15]:
do_df = df.melt(
    id_vars=["sr_no", "location"],
    value_vars=["do_2011", "do_2012", "do_2013", "do_2014", "do_2015"],
    var_name="year",
    value_name="do"
)

do_df["year"] = do_df["year"].str.extract(r"(\d{4})").astype(int)

In [16]:
bod_df = df.melt(
    id_vars=["sr_no", "location"],
    value_vars=["bod_2011", "bod_2012", "bod_2013", "bod_2014", "bod_2015"],
    var_name="year",
    value_name="bod"
)

bod_df["year"] = bod_df["year"].str.extract(r"(\d{4})").astype(int)

In [17]:
fecal_df = df.melt(
    id_vars=["sr_no", "location"],
    value_vars=[
        "fecal_coliform_2011",
        "fecal_coliform_2012",
        "fecal_coliform_2013",
        "fecal_coliform_2014",
        "fecal_coliform_2015"
    ],
    var_name="year",
    value_name="fecal_coliform"
)

fecal_df["year"] = fecal_df["year"].str.extract(r"(\d{4})").astype(int)

In [18]:
clean_df = do_df[["sr_no", "location", "year", "do"]].merge(
    bod_df[["sr_no", "year", "bod"]],
    on=["sr_no", "year"]
).merge(
    fecal_df[["sr_no", "year", "fecal_coliform"]],
    on=["sr_no", "year"]
)

In [19]:
clean_df.head(10)

,sr_no,location,year,do,bod,fecal_coliform
0,1,GANGA AT HARIDWAR D/S,2011,6.7,5.6,1150.0
1,2,GANGA AT GARHMUKTESHWAR,2011,8.2,3.4,1162.0
2,3,GANGA AT KANNAUJ U/S (RAJGHAT),2011,7.9,4.5,3042.0
3,4,"GANGA AT KANNAUJ D/S, U.P",2011,7.8,5.5,3508.0
4,5,GANGA AT KANPUR U/S (RANIGHAT),2011,8.6,4.3,6667.0
5,6,GANGA AT KANPUR D/S (JAJMAU PUMPING STATION),2011,6.9,8.4,38942.0
6,7,"GANGA AT ALLAHABAD D/S (SANGAM), U.P.",2011,7.2,4.0,3408.0
7,8,"GANGA AT VARANASI D/S (MALVIYA BRIDGE), U.P",2011,7.1,8.0,40000.0
8,9,GANGA AT TRIGHAT (GHAZIPUR),2011,7.3,4.3,13000.0
9,10,GANGA AT DAKSHINESHWAR,2011,7.8,4.0,270333.0

In [20]:
clean_df.info()
clean_df.isnull().sum()
clean_df.describe()
clean_df["year"].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sr_no           50 non-null     int64
 1   location        50 non-null     object
 2   year            50 non-null     int64
 3   do              50 non-null     float64
 4   bod             50 non-null     float64
 5   fecal_coliform  47 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.5+ KB

array([2011, 2012, 2013, 2014, 2015])

In [21]:
clean_df.to_csv(
    "/content/ganga_water_quality_clean.csv",
    index=False
)

In [22]:
from google.colab import files

files.download("/content/ganga_water_quality_clean.csv")

In [23]:
clean_df = clean_df.drop(columns=["sr_no"])

In [24]:
clean_df.head()

                         location  year   do  bod  fecal_coliform
0           GANGA AT HARIDWAR D/S  2011  6.7  5.6          1150.0
1         GANGA AT GARHMUKTESHWAR  2011  8.2  3.4          1162.0
2  GANGA AT KANNAUJ U/S (RAJGHAT)  2011  7.9  4.5          3042.0
3       GANGA AT KANNAUJ D/S, U.P  2011  7.8  5.5          3508.0
4  GANGA AT KANPUR U/S (RANIGHAT)  2011  8.6  4.3          6667.0

In [25]:
clean_df = clean_df.dropna(how="all")

In [26]:
print(clean_df.shape)

(50, 5)